### ISSUE TITLE
Current patch timer issue

### ISSUE THREAD

**Issue by tremenmusic** [Yurihaia/HollowKnight-Timer#5]
on the current patch version of hktimer, when entering room transitions, the timer seems to jump up by an arbitrary amount based on load time, around .05 to .2 seconds is what i have noticed. can add up over longer timings. I have not noticed this issue on 1.2.2.1.

**Comment by Yurihaia** [comment]
are you sure this is the latest binary? this sounds like a bug I fixed before and I checked the timer code, 1.5.xx should have the exact same logic as 1.2.2.1.
